/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IClaimStakingRewardsHelperInterface extends ethers.utils.Interface {
  functions: {
    "claimAllRewards(address)": FunctionFragment;
    "claimAllRewardsAndStake(address)": FunctionFragment;
    "claimAndStake(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimAllRewards",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAllRewardsAndStake",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAndStake",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimAllRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAllRewardsAndStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAndStake",
    data: BytesLike
  ): Result;

  events: {};
}

export class IClaimStakingRewardsHelper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IClaimStakingRewardsHelperInterface;

  functions: {
    claimAllRewards(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimAllRewards(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claimAllRewardsAndStake(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimAllRewardsAndStake(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claimAndStake(
      to: string,
      stakeToken: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimAndStake(address,address)"(
      to: string,
      stakeToken: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  claimAllRewards(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimAllRewards(address)"(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claimAllRewardsAndStake(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimAllRewardsAndStake(address)"(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claimAndStake(
    to: string,
    stakeToken: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimAndStake(address,address)"(
    to: string,
    stakeToken: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    claimAllRewards(to: string, overrides?: CallOverrides): Promise<BigNumber>;

    "claimAllRewards(address)"(
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimAllRewardsAndStake(
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "claimAllRewardsAndStake(address)"(
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    claimAndStake(
      to: string,
      stakeToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "claimAndStake(address,address)"(
      to: string,
      stakeToken: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    claimAllRewards(to: string, overrides?: Overrides): Promise<BigNumber>;

    "claimAllRewards(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    claimAllRewardsAndStake(
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claimAllRewardsAndStake(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    claimAndStake(
      to: string,
      stakeToken: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claimAndStake(address,address)"(
      to: string,
      stakeToken: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimAllRewards(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimAllRewards(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claimAllRewardsAndStake(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimAllRewardsAndStake(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claimAndStake(
      to: string,
      stakeToken: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimAndStake(address,address)"(
      to: string,
      stakeToken: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
