/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ILendToAaveMigratorInterface extends ethers.utils.Interface {
  functions: {
    "LEND()": FunctionFragment;
    "migrateFromLEND(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "LEND", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "migrateFromLEND",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "LEND", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "migrateFromLEND",
    data: BytesLike
  ): Result;

  events: {};
}

export class ILendToAaveMigrator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ILendToAaveMigratorInterface;

  functions: {
    LEND(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "LEND()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    migrateFromLEND(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "migrateFromLEND(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  LEND(overrides?: CallOverrides): Promise<string>;

  "LEND()"(overrides?: CallOverrides): Promise<string>;

  migrateFromLEND(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "migrateFromLEND(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    LEND(overrides?: CallOverrides): Promise<string>;

    "LEND()"(overrides?: CallOverrides): Promise<string>;

    migrateFromLEND(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "migrateFromLEND(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    LEND(overrides?: CallOverrides): Promise<BigNumber>;

    "LEND()"(overrides?: CallOverrides): Promise<BigNumber>;

    migrateFromLEND(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "migrateFromLEND(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    LEND(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "LEND()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    migrateFromLEND(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "migrateFromLEND(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
