/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IAaveProtoGovernance } from "../IAaveProtoGovernance";

export class IAaveProtoGovernance__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAaveProtoGovernance {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAaveProtoGovernance;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
    ],
    name: "cancelVoteByVoter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "_voters",
        type: "address[]",
      },
    ],
    name: "challengeVoters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_proposalType",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_ipfsHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_threshold",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_proposalExecutor",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_votingBlocksDuration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_validatingBlocksDuration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxMovesToVotingAllowed",
        type: "uint256",
      },
    ],
    name: "newProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
    ],
    name: "resolveProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_vote",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
    ],
    name: "submitVoteByVoter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
    ],
    name: "tryToMoveToValidating",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
