/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IClaimStakingRewardsHelper } from "../IClaimStakingRewardsHelper";

export class IClaimStakingRewardsHelper__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IClaimStakingRewardsHelper {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IClaimStakingRewardsHelper;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "claimAllRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "claimAllRewardsAndStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
